/**
 * Copyright 2016 Frédéric Massart
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import LocalizedStrings from 'react-native-localization';

const EN = {
  appraisal_attrs_instinct_s0: "Its stats are the best I've ever seen! No doubt about it!",
  appraisal_attrs_instinct_s1: "Its stats are really strong! Impressive.",
  appraisal_attrs_instinct_s2: "It's definitely got some good stats. Definitely!",
  appraisal_attrs_instinct_s3: "Its stats are all right, but kinda basic, as far as I can see.",
  appraisal_attrs_instinct_title: 'Best qualities',
  appraisal_attrs_mystic_s0: "Its stats exceed my calculations. It's incredible!",
  appraisal_attrs_mystic_s1: "I am certainly impressed by its stats, I must say.",
  appraisal_attrs_mystic_s2: "Its stats are noticeably trending to the positive.",
  appraisal_attrs_mystic_s3: "Its stats are not out of the norm, in my estimation.",
  appraisal_attrs_mystic_title: 'Best attributes',
  appraisal_attrs_valor_s0: "I'm blown away by its stats. WOW!",
  appraisal_attrs_valor_s1: "It's got excellent stats! How exciting!",
  appraisal_attrs_valor_s2: "Its stats indicate that in battle, it'll get the job done.",
  appraisal_attrs_valor_s3: "Its stats don't point to greatness in battle.",
  appraisal_attrs_valor_title: 'Strongest features',
  appraisal_level_instinct_heading: 'Overall, your Pokémon...',
  appraisal_level_instinct_l0: '...looks like it can really battle with the best of them!',
  appraisal_level_instinct_l1: '...is really strong!',
  appraisal_level_instinct_l2: '...is pretty decent!',
  appraisal_level_instinct_l3: '...has room for improvement as far as battling goes.',
  appraisal_level_mystic_heading: 'Overall, your Pokémon...',
  appraisal_level_mystic_l0: '...is a wonder! What a breathtaking Pokémon!',
  appraisal_level_mystic_l1: '...has certainly caught my attention.',
  appraisal_level_mystic_l2: '...is above average.',
  appraisal_level_mystic_l3: '...is not likely to make much headway in battle.',
  appraisal_level_valor_heading: 'Overall, your Pokémon...',
  appraisal_level_valor_l0: '...simply amazes me. It can accomplish anything!',
  appraisal_level_valor_l1: '...is a strong Pokémon. You should be proud!',
  appraisal_level_valor_l2: '...is a decent Pokémon',
  appraisal_level_valor_l3: '...may not be great in battle, but I still like it!',
  attack: 'Attack',
  attacking: 'Attacking',
  attributes: 'Attributes',
  charges: 'Charges',
  criticalchance: 'Crit. chance',
  damage: 'Damage',
  defending: 'Defending',
  defense: 'Defense',
  dps: 'DPS',
  duration: 'Duration',
  eggType: 'Egg type',
  energeyincrease: 'Energy increase',
  evolutioncost: 'Evolution cost',
  hp: 'HP',
  instinct: 'Instinct',
  km: 'km',
  moves: 'Moves',
  mystic: 'Mystic',
  name: 'Name',
  none: 'None',
  nonemale: 'None',
  noneresistant: 'None',
  noneweak: 'None',
  notveryeffective: 'Not very effective',
  number: 'Number',
  overall: 'Overall',
  pickYourTeam: 'Pick your team',
  resistant: 'Resistant',
  supereffective: 'Super effective',
  type: 'Type',
  valor: 'Valor',
  weak: 'Weak',
  whoopsinfomissing: 'Whoops, this information is missing...',
}

const FR = {
  appraisal_attrs_instinct_s0: "Ses stats sont les meilleures que j'ai jamais vues ! Sans aucun doute !",
  appraisal_attrs_instinct_s1: "Ses stats sont super élevées. Impressionnant !",
  appraisal_attrs_instinct_s2: "Il a quelques bonnes stats, c'est sûr !",
  appraisal_attrs_instinct_s3: "Ses stats ne sont pas mal, mais un peu basiques, il me semble.",
  appraisal_attrs_instinct_title: 'Meilleurs atouts',
  appraisal_attrs_mystic_s0: "Ses stats dépassent tous mes calculs, c'est incroyable !",
  appraisal_attrs_mystic_s1: "Je suis impressionnée par ses stats, à vrai dire.",
  appraisal_attrs_mystic_s2: "Ses stats s'améliorent à vue d'œil.",
  appraisal_attrs_mystic_s3: "Ses stats n'ont rien d'anormal, à priori.",
  appraisal_attrs_mystic_title: 'Meilleurs atouts',
  appraisal_attrs_valor_s0: "Je suis estomaquée par ses stats. Bravo !",
  appraisal_attrs_valor_s1: "Ses stats sont excellentes ! C'est super !",
  appraisal_attrs_valor_s2: "Ses stats indiquent qu'il va faire des dégâts au combat.",
  appraisal_attrs_valor_s3: "Ses stats ne t'aideront pas beaucoup au combat.",
  appraisal_attrs_valor_title: 'Meilleurs atouts',
  appraisal_level_instinct_heading: 'Ton Pokémon...',
  appraisal_level_instinct_l0: '...semble capable de tenir tête aux meilleurs.',
  appraisal_level_instinct_l1: '...est vraiment fort !',
  appraisal_level_instinct_l2: '...est plutôt bien !',
  appraisal_level_instinct_l3: '...peut devenir un meilleur combattant.',
  appraisal_level_mystic_heading: 'Ton Pokémon...',
  appraisal_level_mystic_l0: '...est une merveille. Un Pokémon captivant.',
  appraisal_level_mystic_l1: '...a retenu toute mon attention.',
  appraisal_level_mystic_l2: '...est supérieur à la moyenne.',
  appraisal_level_mystic_l3: "...n'ira pas très loin au combat.",
  appraisal_level_valor_heading: 'Ton Pokémon...',
  appraisal_level_valor_l0: "...m'étonne beaucoup, il peut tout faire.",
  appraisal_level_valor_l1: '...est très fort, tu dois être fier !',
  appraisal_level_valor_l2: '...est un Pokémon solide.',
  appraisal_level_valor_l3: "...n'est pas un combattant, mais je l'aime bien !",
  attack: 'Attaque',
  attacking: 'Attaque',
  attributes: 'Caractéristiques',
  charges: 'Recharges',
  criticalchance: 'Chance crit.',
  damage: 'Dégâts',
  defending: 'Défense',
  defense: 'Défense',
  dps: 'DPS',
  duration: 'Durée',
  eggType: 'Type d\'œuf',
  energeyincrease: 'Énergie récupérée',
  evolutioncost: 'Coût d\'évolution',
  hp: 'HP',
  instinct: 'Intuition',
  km: 'km',
  moves: 'Attaques',
  mystic: 'Sagesse',
  name: 'Nom',
  none: 'Aucuns',
  nonemale: 'Aucuns',
  noneresistant: 'Aucunes',
  noneweak: 'Aucunes',
  notveryeffective: 'Pas très efficace',
  number: 'Numéro',
  overall: 'Total',
  pickYourTeam: 'Choisis ton équipe',
  resistant: 'Résistant',
  supereffective: 'Super efficace',
  type: 'Type',
  valor: 'Bravoure',
  weak: 'Faible',
  whoopsinfomissing: 'Oups, cette information manque...',
}

export const Strings = new LocalizedStrings({
  en: EN,
  fr: FR
});
